name: Global Express
input: GFM
url: globalexpress.io
markdown: kramdown
permalink: pretty
description: Global Express enables real time cross border payments between different corridors of Africa to the rest of the world, by serving transaction needs for both businesses and individuals using cutting-edge block chain technology, ensuring consistent access and fast settlement.
